import { Product, SellerStat } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Minimalist Leather Backpack',
    price: 120,
    category: 'Accessories',
    image: 'https://picsum.photos/400/500?random=1',
    description: 'Handcrafted from premium leather, designed for the modern urban commuter.',
    rating: 4.8,
    reviews: 124,
  },
  {
    id: '2',
    name: 'Wireless Noise-Canceling Headphones',
    price: 299,
    category: 'Electronics',
    image: 'https://picsum.photos/400/500?random=2',
    description: 'Immersive sound quality with 30-hour battery life and fast charging.',
    rating: 4.9,
    reviews: 890,
  },
  {
    id: '3',
    name: 'Organic Cotton Basic Tee',
    price: 35,
    category: 'Clothing',
    image: 'https://picsum.photos/400/500?random=3',
    description: 'Soft, breathable, and sustainably sourced. A wardrobe essential.',
    rating: 4.5,
    reviews: 56,
  },
  {
    id: '4',
    name: 'Ceramic Pour-Over Set',
    price: 65,
    category: 'Home',
    image: 'https://picsum.photos/400/500?random=4',
    description: 'Brew the perfect cup of coffee with this elegant minimalist set.',
    rating: 4.7,
    reviews: 210,
  },
  {
    id: '5',
    name: 'Limited Edition Digital Sneaker (NFT)',
    price: 500,
    category: 'Collectibles',
    image: 'https://picsum.photos/400/500?random=5',
    description: 'Exclusive digital collectible with physical redeemability token.',
    rating: 5.0,
    reviews: 12,
    isNFT: true,
  },
  {
    id: '6',
    name: 'Smart Home Hub',
    price: 149,
    category: 'Electronics',
    image: 'https://picsum.photos/400/500?random=6',
    description: 'Control your entire home with voice commands and automation.',
    rating: 4.3,
    reviews: 345,
  },
  {
    id: '7',
    name: 'Ergonomic Office Chair',
    price: 450,
    category: 'Furniture',
    image: 'https://picsum.photos/400/500?random=7',
    description: 'Designed for comfort and posture support during long work hours.',
    rating: 4.6,
    reviews: 67,
  },
  {
    id: '8',
    name: 'Abstract Art Print',
    price: 80,
    category: 'Art',
    image: 'https://picsum.photos/400/500?random=8',
    description: 'High-quality giclée print on archival paper. Limited run.',
    rating: 4.8,
    reviews: 23,
  },
];

export const SELLER_STATS: SellerStat[] = [
  { date: 'Mon', sales: 400, visitors: 2400 },
  { date: 'Tue', sales: 300, visitors: 1398 },
  { date: 'Wed', sales: 200, visitors: 9800 },
  { date: 'Thu', sales: 278, visitors: 3908 },
  { date: 'Fri', sales: 189, visitors: 4800 },
  { date: 'Sat', sales: 239, visitors: 3800 },
  { date: 'Sun', sales: 349, visitors: 4300 },
];